GPU: ['2']
TRAIN:
  NUM_AUGMENT_VIEWS: 1
NETWORK:
  TEMPORAL_LENGTH: 7
  TRANSFORM_DIM: 4
  M_FORMER:
    MODE: mtf
H36M_DATA:
  TRAIN_CAMERAS: [0, 2]
  TEST_CAMERAS: [0,1, 2,3]
TEST:
  NUM_FRAMES: [7]
  NUM_VIEWS: [4]